### ISSUE TITLE
how to create date use datapicker?

### ISSUE THREAD

**Issue by andridgitalbox** [pooyamb/wpsamplecrudplugin#1]
hello sir...how to create form date use datapicker ?thanks

**Comment by pooyamb** [comment]
Hi andrinda,
I made some changes and time field is now user fillable and has datepicker,
Thanks

**Comment by andridgitalbox** [comment]
Yes has solved sir.. :D i change text and id='datepicker' work... iam confused if use select choice..and validation insert..you can sir ?

**Comment by pooyamb** [comment]
Hi andrinda,
As it's not what I want to implement in my tutorial and don't have enough time for it, I will answer you here.
For your first question, you can take a look at jquery ui's datepicker for it's configuration,
Take a look at this link :
https://jqueryui.com/datepicker/
If it's not what you want, you can take a look at above link, don't forget to include js file in main class,
https://github.com/vitalets/combodate

for php side validation you can use the function inside model class, or just use main class again,
for learning about how you can do it, search the web, there is a lot of tutorials and Q&As about it depend on what you need.

Edit :
And it's better to use classes for this thing instead of id!
use class='datepicker'
